In [1]:
import pandas as pd

df = pd.read_csv('C:/Users/Tanur/Documents/DATA PROJECTS/1/data/customer_shopping_behavior.csv')

give the top 5 rows to get a sense of  the structure of data

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

overall structure and data types info

In [3]:
df.info()## check the data types and memory usage

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

check the summary statistics of all the numerical columns only

In [4]:
df.describe() ### check the summary statistics of all the numerical columns

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

check the summary statistics of all all the columns numerical and categorical columns

In [5]:
df.describe(include = 'all') ## check the summary statistics of all all the columns numerical and categorical columns

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

check the missing values

In [6]:
df.isnull().sum() ## check the missing values

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

always pick median over mean when trying tro replace missing values because median is robust to outliers preventing skewing of results.

fill the missing with the median review rating within each category. that is it'll be replaced the median value of something within its category

In [7]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median())) ## fill the missing values with the median review rating within each category

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

change to column names to smaller case and snake casing to add in easing typing

In [9]:
df.columns = df.columns.str.lower() #### convert column names to lowercase
df.columns = df.columns.str.replace(' ', '_') ### replace spaces with underscores
df = df.rename(columns={'purchase_amount_(usd)' : 'purchase_amount'}) ## rename the column purchase_amount_(usd) to purchase_amount'''

In [10]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

create a column age_group

In [11]:
#create a column age_group
labels = ['Young Adult', 'Adult', 'Middle Aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels) ## create a column age_group using quantile cut

aids to see how many people are in each age group helping to analyse patterns (understanding customer behaviour) across each category via age/age group

In [12]:
df[['age', 'age_group']].head(10) ## check the first 10 rows of the age and age_group columns

   age    age_group
0   55  Middle Aged
1   19  Young Adult
2   50  Middle Aged
3   21  Young Adult
4   45  Middle Aged
5   46  Middle Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle Aged

create purchase frequency days column

the current sheet shows how often customers shop but its in text format. it needs to be converted into a numerical format so that i can perform calculations on it. i.e number of days btw purchases

In [13]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Biweekly': 14,
    'Annually': 365,
    'Every 3 Months': 90,
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping) ## create a new column purchase_frequency_days by mapping
#the frequency_of_purchases column to the frequency_mapping dictionary)

In [14]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10) ## check the first 10 rows of the purchase_frequency_days and frequency_of_purchases columns']]]

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

check the first 10 rows of the discount_applied and promo_code_used columns to see if both are needed or one is redundanted by the other. If not, remove the column that is not needed. In this case, both are needed so keep them in the dataset. If one is redundant, remove it. For example, if 'discount_applied' is always

In [15]:
df[['discount_applied', 'promo_code_used']].head(10) ## check the first 10 rows of the discount_applied and promo_code_used columns

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [16]:
(df['discount_applied'] == df['promo_code_used']).all() ## check if the discount_applied and promo_code_used columns are the same, if they are the same, we can drop one of them

np.True_

remove promo code used

In [17]:
df = df.drop(['promo_code_used'], axis=1) ## drop the promo_code_used column

In [18]:
df.columns ## check the columns in the dataset to see if they match the expected columns. If not, add the missing columns or remove the extra columns. For example, if 'discount_applied' is always"""

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [19]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.13-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.54-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.6-cp314-cp314-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\tanur\documents\sheffield msc data science\research & disertation\air qaulity dissertation\air_quality_env\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.13-cp314-cp314-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ----------------------------- ---------- 2.1/2.9 MB 13.1 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 14.1 MB/s  0:00:00
Downloading sqlalchemy-2.0.54-cp314-cp314-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 2.2/2.2 MB 30.4 MB/s  0:00:00
Downloading greenlet-3.5.6-cp314-cp314-win_amd64.whl (327 kB)
Installing collected packages: psycopg2-binary, greenlet, sqlalchemy

   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.5.6 psycopg2-binary-2.9.13 sqlalchemy-2.0.54
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
from sqlalchemy import create_engine
#step 1: connect to PostgreSQL database using SQLAlchemy
# replace placeholders with your actual details
username = 'postgres' #default username for PostgreSQL
password = 'admin' #default password for PostgreSQL
host = 'localhost' #if running locally
port = '5432' #default port for PostgreSQL
database = 'customer behavior' #name of the database

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}") ## connect to the database using SQLAlchemy

#step 2: load dataframe into PostgreSQL database
table_name = "customer" #choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False) ## load the dataframe into the PostgreSQL database  

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.") ## print a message to confirm that the data has been loaded successfully

Data successfully loaded into table 'customer' in database 'customer behavior'.

questions to answer
1. what is the total revenue generated by male vs female customers
2. which customer used a discount but still spent more than the average purchase amount
3. which top 5 products with the highest average review rating
4. compare the average purchase aMOUNTS BETWEEN STANDARD AND EXPRESS SHIPPING
5. Do subscribed customers spend more? compare average spend total revenue between subscribers and non subcribers
6. which 5 products have the highets percentage of purchases with discounts applied
7. segment customers into new, returning, and loyal based on thier total number of previous purchases and show the count of each segment
8. what are the top 3 most purchases products within each category
9. are customers whop are repeat buyers (more than 5 previous purchases) also likely to subscribe?
10. what is the revenue contribution of each age